# Generated by Django 4.0.6 on 2022-07-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
